<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.jbk.TestCases.OperatorPageTest" tests="4" time="37.866" ignored="0" failures="1" timestamp="14 Oct 2018 18:21:58 GMT" skipped="0" hostname="DESKTOP-E4PH7S5" errors="0">
  <testcase name="verifyOperatorPageLabel" time="9.076" classname="com.jbk.TestCases.OperatorPageTest"/>
  <testcase name="verifyOperatorTableHeading" time="10.503" classname="com.jbk.TestCases.OperatorPageTest">
    <failure type="java.lang.AssertionError" message="expected [Operator] but found [Reason]">
      <![CDATA[java.lang.AssertionError: expected [Operator] but found [Reason]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.jbk.TestCases.OperatorPageTest.verifyOperatorTableHeading(OperatorPageTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyOperatorTableHeading -->
  <testcase name="verifyOperatorPageTableLabel" time="9.465" classname="com.jbk.TestCases.OperatorPageTest"/>
  <testcase name="verifyOperatorPageTitle" time="8.822" classname="com.jbk.TestCases.OperatorPageTest"/>
</testsuite> <!-- com.jbk.TestCases.OperatorPageTest -->
